//go:build tools

// Comando genmagics imprime as tabelas de números mágicos já validadas,
// para serem gravadas em rules/magics_data.go e evitar a busca aleatória
// a cada arranque do programa.
//
//	go run -tags tools ./internal/tools/genmagics > rules/magics_data.go
package main

import (
	"bufio"
	"fmt"
	"os"

	"github.com/CallMePeterD/chess-ia/rules"
)

func main() {
	out := bufio.NewWriter(os.Stdout)
	defer out.Flush()

	fmt.Fprintln(out, "// Code generated by internal/tools/genmagics. DO NOT EDIT.")
	fmt.Fprintln(out)
	fmt.Fprintln(out, "package rules")
	fmt.Fprintln(out)
	fmt.Fprintln(out, "// Números mágicos já validados para cada casa. São verificados no arranque")
	fmt.Fprintln(out, "// (ver initMagics); se algum falhar, a busca aleatória entra como reserva.")
	dump(out, "rookMagicNumbers", rules.RookMagics)
	fmt.Fprintln(out)
	dump(out, "bishopMagicNumbers", rules.BishopMagics)
}

func dump(out *bufio.Writer, name string, magics [64]uint64) {
	fmt.Fprintf(out, "var %s = [64]uint64{\n", name)
	for _, m := range magics {
		fmt.Fprintf(out, "\t0x%016x,\n", m)
	}
	fmt.Fprintln(out, "}")
}
